package com.model;

/**
 * TGuahao generated by MyEclipse Persistence Tools
 */

public class TGuahao implements java.io.Serializable
{

	private Integer id;
	private Integer zhuanjiaId;
	private Integer userId;
	private String riqi;

	private String jibing;
	private String xingming;
	private String lianxi;
	
	private TZhuanjia zhuanjia;
	
	
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getJibing()
	{
		return jibing;
	}
	public void setJibing(String jibing)
	{
		this.jibing = jibing;
	}
	public String getLianxi()
	{
		return lianxi;
	}
	public void setLianxi(String lianxi)
	{
		this.lianxi = lianxi;
	}
	public String getRiqi()
	{
		return riqi;
	}
	public TZhuanjia getZhuanjia()
	{
		return zhuanjia;
	}
	public void setZhuanjia(TZhuanjia zhuanjia)
	{
		this.zhuanjia = zhuanjia;
	}
	public void setRiqi(String riqi)
	{
		this.riqi = riqi;
	}
	public Integer getUserId()
	{
		return userId;
	}
	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}
	public String getXingming()
	{
		return xingming;
	}
	public void setXingming(String xingming)
	{
		this.xingming = xingming;
	}
	public Integer getZhuanjiaId()
	{
		return zhuanjiaId;
	}
	public void setZhuanjiaId(Integer zhuanjiaId)
	{
		this.zhuanjiaId = zhuanjiaId;
	}

}