package com.model;

/**
 * TZhuanjia generated by MyEclipse Persistence Tools
 */

public class TZhuanjia implements java.io.Serializable
{

	private Integer id;
	private int yiyuanId;
	private int keshiId;
	private String xingming;
	
	private String xingbie;
	private Integer nianling;
	private String shanchang;
	private String leixing;//专家门诊--普通门诊
	
	private String fujian;
	private String del;
	
	private TKeshi keshi;
    private TYiyuan yiyuan;
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public int getYiyuanId()
	{
		return yiyuanId;
	}
	public void setYiyuanId(int yiyuanId)
	{
		this.yiyuanId = yiyuanId;
	}
	public int getKeshiId()
	{
		return keshiId;
	}
	public void setKeshiId(int keshiId)
	{
		this.keshiId = keshiId;
	}
	public String getXingming()
	{
		return xingming;
	}
	public void setXingming(String xingming)
	{
		this.xingming = xingming;
	}
	public String getXingbie()
	{
		return xingbie;
	}
	public void setXingbie(String xingbie)
	{
		this.xingbie = xingbie;
	}
	public Integer getNianling()
	{
		return nianling;
	}
	public void setNianling(Integer nianling)
	{
		this.nianling = nianling;
	}
	public String getShanchang()
	{
		return shanchang;
	}
	public void setShanchang(String shanchang)
	{
		this.shanchang = shanchang;
	}
	public String getLeixing()
	{
		return leixing;
	}
	public void setLeixing(String leixing)
	{
		this.leixing = leixing;
	}
	public String getFujian()
	{
		return fujian;
	}
	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public TKeshi getKeshi()
	{
		return keshi;
	}
	public void setKeshi(TKeshi keshi)
	{
		this.keshi = keshi;
	}
	public TYiyuan getYiyuan()
	{
		return yiyuan;
	}
	public void setYiyuan(TYiyuan yiyuan)
	{
		this.yiyuan = yiyuan;
	}
	
}